---
title: "Tipos de filme de Will Smith"
output:
    html_document:
    df_print: paged
theme: sandstone
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse, warn.conflicts = F)
library(rvest)
library(plotly)
library(cluster)
library(ggdendro)
library(gridExtra)
source(here::here("code/lib.R"))
source(here::here("code/plota_solucoes_hclust.R"))
theme_set(theme_report())

knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5,
                      echo = TRUE)

paleta = c("#404E4D",
           "#92DCE5",
           "#938BA1",
           "#2D3142",
           "#F4743B")
```

```{r}
## ANTES DE USAR
# Para criar data/movies.csv
# import_data("tom_cruise") ou com o ator/atriz que você escolher
import_data("vin_diesel")
```


```{r read}
filmes = read_imported_data()
```


```{r}
agrupamento_h_2d = filmes %>% 
    as.data.frame() %>% 
    column_to_rownames("filme") %>%
    select(avaliacao, bilheteria) %>%
    dist(method = "euclidean") %>% 
    hclust(method = "centroid")

ggdendrogram(agrupamento_h_2d, rotate = TRUE)

data.frame(height = agrupamento_h_2d$height) %>% 
    mutate(k = 1:n()) %>% 
    ggplot(aes(x = k, y = height)) + 
    geom_line(colour = "grey") + 
    geom_point() + 
    labs(x = "Número de clusters produzido", y = "Dissimilaridade na junção")

plota_hclusts_2d(agrupamento_h_2d, 
                 filmes, 
                 c("avaliacao", "bilheteria"), 
                 linkage_method = "centroid", ks = 1:6) 
```

```{r}
agrupamento_h_2d = filmes %>% 
    mutate_at(vars(avaliacao, bilheteria), 
              funs(scale)) %>% 
    as.data.frame() %>% 
    column_to_rownames("filme") %>%
    select(avaliacao, bilheteria) %>%
    dist(method = "euclidean") %>% 
    hclust(method = "centroid")

ggdendrogram(agrupamento_h_2d, rotate = TRUE, theme_dendro = F)

plota_hclusts_2d(agrupamento_h_2d, 
                 filmes, 
                 c("avaliacao", "bilheteria"), 
                 linkage_method = "ward.D", ks = 1:6) 
```

```{r}
agrupamento_h_2d = filmes %>% 
    mutate(`BOX OFFICE` = log10(bilheteria)) %>%
    mutate_at(vars(avaliacao, bilheteria), funs(scale)) %>%
    as.data.frame() %>% 
    column_to_rownames("filme") %>%
    select(avaliacao, bilheteria) %>%
    dist(method = "euclidean") %>% 
    hclust(method = "ward.D")

ggdendrogram(agrupamento_h_2d, rotate = TRUE, theme_dendro = F)

filmes2 = filmes %>% mutate(bilheteria = log10(bilheteria))
plota_hclusts_2d(agrupamento_h_2d, 
                 filmes2, 
                 c("avaliacao", "bilheteria"), 
                 linkage_method = "ward.D", ks = 1:6) + 
    scale_y_log10() + 
    scale_color_brewer(palette = "Dark2")

plota_hclusts_2d(agrupamento_h_2d, 
                 filmes2, 
                 c("avaliacao", "bilheteria"), 
                 linkage_method = "ward.D", ks = 1:6) + 
    scale_color_brewer(palette = "Dark2")
```

```{r}
filmes2 = filmes %>% 
    mutate(TITLE_LENGTH = nchar(filme))

glimpse(filmes2)

dists = filmes2 %>% 
    as.data.frame() %>% 
    mutate(bilheteria = log10(bilheteria)) %>% 
    mutate_at(vars(avaliacao, 
                   bilheteria, 
                   TITLE_LENGTH, 
                   ano), 
              funs(scale)) %>% 
    column_to_rownames("filme") %>%
    select(avaliacao, bilheteria, TITLE_LENGTH, ano) %>%
    dist(method = "euclidean")

agrupamento_h_md = dists %>% 
    hclust(method = "ward.D")

ggdendrogram(agrupamento_h_md, rotate = T)

tibble(alturas_dendrograma = agrupamento_h_md$height) %>% 
    mutate(k = 1:n()) %>% 
    ggplot(aes(x = k, y = alturas_dendrograma)) + 
    geom_line(colour = "grey") + 
    geom_point() + 
    labs(x = "Junções feitas (34 - clusters)", 
         y = "Dissimilaridade na junção", 
         title = "Dissimilaridade em cada aglomeração")

```

